### ISSUE TITLE
Feature Value fails in multiprocess environment

### ISSUE THREAD

**Issue by sameerjj** [growthbook/growthbook-kotlin#103]
I have a ForegroundService which requires a feature flag, I declare it to have a separate process in the manifest:
`android:process=":location"`

when I call 
`gb.feature("baseurl").value as String`
it fails, despite it working in the main process.

**Comment by sameerjj** [comment]
sample initialization code:
```
val gb = GBSDKBuilder(
                apiKey = "sdk-key",
                hostURL = "https://cdn.growthbook.io/",
                networkDispatcher = DefaultGBNetworkClient(),
                attributes = mapOf("app_id" to appId),
                trackingCallback = { gbExperiment, gbExperimentResult ->
                    Log.d(TAG, "Variation Id: ${gbExperimentResult.variationId}")
                },
            ).initialize()
            
            val baseUrl = gb.feature("samplekey").value as String
            val legacyEndpoints = gb.feature("sampleflag").off
            
```

**Comment by Bohdan-Kim** [comment]
Hello @sameerjj 
Could you please give us more details about "fails".
Is it `java.lang.NullPointerException`?

**Comment by Bohdan-Kim** [comment]
Try to use 
`gb.feature("baseurl").value as String?`
instead of
`gb.feature("baseurl").value as String`

**Comment by sameerjj** [comment]
Yes null pointer exception - the features don’t exist in that process (my
guess would be the cache is in the memory of the other process but still
marked as “saved “)

The value is null so casting to optional doesn’t really solve the issue as
the feature definitely exists and works in the main app

**Comment by sameerjj** [comment]
Hi @Bohdan-Kim, is there a way to know when the initialization is complete? `.initialize()` is synchronous in latest version 1.1.48

**Comment by sameerjj** [comment]
btw, I induced a delay of 1 second between `initialize()` and the use of the feature, and it still didn't work in the foreground service separate process. I also tried a retry mechanism. It simply doesn't load here.
Anyways, I'm just going to use my own cache, but there's definitely an issue here

**Comment by Bohdan-Kim** [comment]
`CoroutineDispatcher` in `Dispatcher.kt` is not initialized if user didn't open the application and has the foreground service only. The issue is hard to reproduce.

**Comment by Bohdan-Kim** [comment]
``
is there a way to know when the initialization is complete?
``
`setRefreshHandler()` in `GBSDKBuilder` class. `setRefreshHandler()` can be used to be notified about features refresh.

**Comment by Bohdan-Kim** [comment]
We tried just to wrap the code with `thread {}`. Everything works the same. We understand that it is not the foreground service.

**Comment by Bohdan-Kim** [comment]
It seems like we reproduced the issue.

**Comment by Bohdan-Kim** [comment]
This foreground service works fine for me:
https://gist.github.com/Bohdan-Kim/d2dd0f0871fe3019996e7adab368d79d

**Comment by sameerjj** [comment]
Hi @Bohdan-Kim, you would have to add to your manifest that it's a separate process as I mentioned
Hi @Bohdan-Kim, you would have to 
```
<service
            android:name="com.example.growthbookdemoapp.ForegroundService"
            android:exported="false"
            android:foregroundServiceType="location"
            android:process=":location" />
```

**Comment by Bohdan-Kim** [comment]
We followed your instruction and noticed that when `foregroundServiceType ` and `process` attributes applied the features list are not restored from cache.

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-kotlin/pull/105) was created according to this issue.
After merge in `main` branch there will be an option to pass `Service` context to the GrowthBook SDK. For similar issues we will ask to paste this line:
```
CachingAndroid.consumeContext(this)
```
where `this` is a reference to a Service instance.

**Comment by Bohdan-Kim** [comment]
We released v1.1.58 version of the SDK. The changes from pull request are available in v1.1.58

**Comment by sameerjj** [comment]
thanks @Bohdan-Kim. I'm unable to test this because any version above `1.1.47` the library doesn't import properly for me
<img width="354" alt="Screenshot 2024-05-27 at 5 12 59 PM" src="https://github.com/growthbook/growthbook-kotlin/assets/7051257/9c3f86e4-1f98-487a-9d63-b032675741ab">

**Comment by Bohdan-Kim** [comment]
It's strange. What could be the cause of this? Do you use the SDK in application module or in some other module?
![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/867fb4c7-d1ba-45a8-b531-fe9ba991b8a9)

**Comment by Bohdan-Kim** [comment]
@sameerjj  Have you included `mavenCentral()` repository?

**Comment by sameerjj** [comment]
Hi @Bohdan-Kim I have, I was only able to resolve the import issue with 
```
api 'io.growthbook.sdk:GrowthBook-android:1.1.58'
implementation 'io.ktor:ktor-client:2.3.11'
```

For the original issue, it seems if I call `CachingAndroid.consumeContext(context)` in my foreground service before making the initialize() call, that it works correctly. I believe we can close this issue. Thanks
