### ISSUE TITLE
Growthbook requires ktor dependency

### ISSUE THREAD

**Issue by Sereekjan** [growthbook/growthbook-kotlin#112]
Seems like `DefaultGBNetworkClient` with `ktor` dependency should be moved into different artifact (like `GrowthBook-ktor`)
Because of the following issue:

![photo_2024-05-28 12 48 49 (1)](https://github.com/growthbook/growthbook-kotlin/assets/17454145/c43d74c2-bf5e-43fd-adee-798d1502b5a8)

Using different http client requires downloading (transitive way) useless `ktor` dependencies

![photo_2024-05-28 12 48 49](https://github.com/growthbook/growthbook-kotlin/assets/17454145/3403622a-4e12-435c-9ac5-8b3c411054fb)

**Comment by sameerjj** [comment]
I'm having this issue as well
in fact `api 'io.growthbook.sdk:GrowthBook:1.1.58'` doesn't even work for me, I manage to get to the state above with
`api 'io.growthbook.sdk:GrowthBook-android:1.1.58'` (not mentioned in documentation)

**Comment by Sereekjan** [comment]
You are correct, implementation of the `ktor` library fixing the error with "Cannot access class 'io.ktor.HttpClient'"

But I don't want implement it, cause I'm using different http client, and I'm going to make a custom implementation of NetworkDispatcher with my case.

Anyway still waiting for the removing `ktor` dependency from this library

**Comment by Bohdan-Kim** [comment]
We agree. `ktor` dependency should be moved into other artifact.

**Comment by Bohdan-Kim** [comment]
What do you think about `complileOnly` configuration for `ktor` instead of `implementation` configuration? We are proposing this as temporary while moving into other artifact.
![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/5ed48b9a-7313-4723-8dde-8257db1901cb)

**Comment by Sereekjan** [comment]
For me current implementation is also ok, but when the update will be merged, I'll get rid of this dependency

**Comment by Bohdan-Kim** [comment]
According to this issue `ktor` dependency was moved to the other artifact. We named this artifact `DefaultNetworkDispatcher`. After these changes had been made, v1.1.59 was released.
@Serikzhan could you please test v1.1.59?
![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/6c53111e-ee7a-4ee7-b2f0-ea0e7fe21e89)

**Comment by Bohdan-Kim** [comment]
@Sereekjan Could you please specify which Http client you are using?

**Comment by chitho87** [comment]
omg, pls update your doc the name "DefaultGBNetworkClient" to "DefaultGBNetworkDispatcher" it took me the whole morning to figure out what's  wrong

**Comment by Bohdan-Kim** [comment]
😅

**Comment by Sereekjan** [comment]
Thank you!
Currently I'm using retrofit, but I'm thinking of moving to ktor
