### ISSUE TITLE
SDK Exception Handling

### ISSUE THREAD

**Issue by evgenkr47** [growthbook/growthbook-kotlin#114]
Hello! Could you please advise on error handling in the SDK? The issue is that I'm using DefaultGBNetworkClient() as a networkDispatcher, and it successfully handles HttpException (422, 420, etc.). However, if I disconnect from the internet and there's a call to gbBuilder, it crashes with FATAL EXCEPTION: DefaultDispatcher-worker-2. Also, if the request times out, I get another crash with FATAL EXCEPTION: DefaultDispatcher-worker-3, io.ktor.client.network.sockets.SocketTimeoutException: Socket timeout has expired. How can I catch these errors? I couldn't find anything in the documentation regarding error handling, and try/catch also doesn't help, nor does writing my custom networkDispatcher.

```
private var growthBookSDK: GrowthBookSDK? = null
private val networkDispatcher by lazy { DefaultGBNetworkClient() }

val gbBuilder: GBSDKBuilder =
        if (BuildConfig.DEBUG) {
            GBSDKBuilder(
                apiKey = debugApiKey,
                hostURL = hostURL,
                attributes = mutableMapOf(),
                networkDispatcher = networkDispatcher,
                trackingCallback = { gbExperiment, gbExperimentResult ->
                    AppLog.print("Viewed Experiment")
                    AppLog.print("Experiment Id: " + gbExperiment.key)
                    AppLog.print("Variation Id: " + gbExperimentResult.variationId)
                }
            )
        } else {
            GBSDKBuilder(
                apiKey = releaseApiKey,
                hostURL = hostURL,
                attributes = mutableMapOf(),
                networkDispatcher = networkDispatcher,
                trackingCallback = { gbExperiment, gbExperimentResult ->
                    AppLog.print("Viewed Experiment")
                    AppLog.print("Experiment Id: " + gbExperiment.key)
                    AppLog.print("Variation Id: " + gbExperimentResult.variationId)
                }
            )
        }
        
        fun initializeFeauteres() {
        gbBuilder.setRefreshHandler { b, gbError ->
            FeatureToggles.values().forEach {
                growthBookSDK?.feature(it.toggleName)?.on
            }
        }
        growthBookSDK = gbBuilder.initialize()
    }
```

**Comment by vazarkevych** [comment]
Hi, we will fix this issue in our next release. Thank you for reporting it.

**Comment by sbelloz** [comment]
Do you mind releasing this fix ASAP? We are experiencing crashes in production.

For now, a simple solution is to rewrite this method, where the exception seems to occur.

```kotlin
override fun consumeGETRequest(
        request: String,
        onSuccess: (String) -> Unit,
        onError: (Throwable) -> Unit
    ): Job = CoroutineScope(Dispatchers.IO).launch {
        try {
            val result = httpClient.get(request)
            onSuccess(result.body())
        } catch (ex: Exception) {
            onError(ex)
        }
    }
 ```

**Comment by vazarkevych** [comment]
Hi, @sbelloz. We will work on that for providing a new release as soon as possible.

**Comment by MykytaSalohub** [comment]
Hi, @sbelloz you can try new release: `implementation 'io.growthbook.sdk:DefaultNetworkDispatcher:1.0.1'` - where this bug was fixed

**Comment by sbelloz** [comment]
Hey @vazarkevych We're experiencing some crashes due to `SSLHandshakeException`. Why wasn't it included in the try-catch? 
And why don't you wrap the client to catch all possible exceptions?

**Comment by vazarkevych** [comment]
Hi, @sbelloz. Thank you for providing the information. We will check it and write to you after we have found the right solution.

**Comment by Bohdan-Kim** [comment]
Hello @sbelloz 
We added `SSLHandshakeException` `IOException` and `Exception` types in [this pull request](https://github.com/growthbook/growthbook-kotlin/pull/122).

**Comment by ninniuz** [comment]
@Bohdan-Kim thanks for your support.
When are you expecting to release a patch version with this fix?

**Comment by Bohdan-Kim** [comment]
1.0.2 version of NetworkDispatcherKtor appeared on the Maven repository.
```
dependencies {
     implementation 'io.growthbook.sdk:NetworkDispatcherKtor:1.0.2' 
}
```

`NetworkDispatcherKtor` is the new name for `DefaultNetworkDispatcher` artifact.
The main class of `NetworkDispatcherKtor` module is `GBNetworkDispatcherKtor`
