### ISSUE TITLE
Issue with Ktor dependencies: failed resolution of ContentNegotiation

### ISSUE THREAD

**Issue by jpgpuyo** [growthbook/growthbook-kotlin#125]
Hello,

I have found an issue when using GBNetworkDispatcherKtor.
For me, this is happening with versions 1.1.59 and version 1.1.60. Not sure about another versions.
I'm using the io.growthbook.sdk:NetworkDispatcherKtor:1.0.2

```
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/plugins/contentnegotiation/ContentNegotiation;
at com.sdk.growthbook.network.GBNetworkDispatcherKtorKt$createDefaultHttpClient$1.invoke(GBNetworkDispatcherKtor.kt:34)
```
I have added the dependency io.ktor:ktor-client-content-negotiation, but still failing.

If it helps, in my project I am already using ktor, and I'm using the ktor version 3.0.0-beta-1

Any hint? Thanks!

**Comment by Bohdan-Kim** [comment]
Hello, 
I've reproduced `java.lang.NoClassDefFoundError`. It happened to me when I was using `ktor-client-core:3.0.0-beta-1`.
Changing `ktor-client-core` version from `3.0.0-beta-1` to `2.3.12` solved the issue for me.

**Comment by jpgpuyo** [comment]
Not sure if the fix should be done in Growthbook SDK or in ktor, but it is good to know that at least we can use stable version of Ktor or use another network client :)

**Comment by vazarkevych** [comment]
Hi, @jpgpuyo. Did that work for you?

**Comment by jpgpuyo** [comment]
@vazarkevych I'm using NetworkDispatcher from Okhttp, but both solutions are working. Thanks!
