### ISSUE TITLE
400 errors caused by inaccurately returning a success response.

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook-kotlin#128]
We are using the ‘io.growthbook.sdk:NetworkDispatcherOkHttp:1.0.0’ and we have seen that when we get an error, for example Invalid API Key:

{
‘status": 400,
‘error": ’Invalid API Key’
}

The response goes to the OnResponse of the GBNetworkDispatcherOkHttp class, it detects that the response was unsuccessful and returns an exception using the ‘onError’. It then goes through the onSuccess and returns that the response was successful when it should not have been, as it was an error. Attached screenshot of why the error occurs.

Also, we have seen that if the app calls a URL that doesn't exist, the app closes returning: ‘FATAL EXCEPTION: OkHttp Dispatcher’. It seems to be because it tries to return the call as successful.

Submitted on behalf of customer

<img width="887" alt="image" src="https://github.com/user-attachments/assets/59c88820-d08e-4e5b-88a2-944d147a1a96">

**Comment by Bohdan-Kim** [comment]
Hello @natasha-growthbook!
Thanks for reporting this issue.
It really seems like the code you are pointing to is written wrong. We'll correct it.

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-kotlin/pull/129) was created according to this issue.
