### ISSUE TITLE
Proposal: extend GBSDKBuilderApp, add setCustomFeaturePath(path)

### ISSUE THREAD

**Issue by VovaStelmashchuk** [growthbook/growthbook-kotlin#13]
Proposal
Extend API, allow developer to changes path "api/features/".

Use case:
We using self hosted growthbook.
Our data flow:
Client -> CDN -> Proxy (the proxy can modify request) -> Growthbook
The proxy has the following routing.
https://our_host.com/growthbook/api/features/{$1} -> http://our_growth_book_instance/api/features{$1}

Extend API.
Add new method to `GBSDKBuilderApp `
```kotlin
fun setCustomFeaturePath(customPath: String): GBSDKBuilderApp
```

I can implement the feature. 

Will these changes be consistencies with growthbook ?

**Comment by jdorn** [comment]
Our other SDKs allow passing in a JSON object with feature definitions instead of specifying a host and API key. So the user is responsible for fetching and caching the features. Would that work better for your use case?

**Comment by VovaStelmashchuk** [comment]
Your way works for me too. We will have consistency with other growth book sdk. 

My proposal:
Add a new public method

```kotlin
fun getFeatures(rawGBResponse: String, attributes: Map<String, Any>, val forcedVariations: Map<String, Int>, val qaMode : Boolean) : GBFeatures
```

**Comment by vazarkevych** [comment]
Hi Vova, is this issue is still relevant for you? We are going to look at it.

**Comment by VovaStelmashchuk** [comment]
Currently we migrate to internal fork, The issue not relevant for me now.
