### ISSUE TITLE
Release does not exist

### ISSUE THREAD

**Issue by VovaStelmashchuk** [growthbook/growthbook-kotlin#19]
Any release after 1.1.1 does not exist in maven central.

[MavenCentral](https://search.maven.org/search?q=g:io.growthbook.sdk%20AND%20a:GrowthBook)

**Comment by jdorn** [comment]
Thanks, I forgot to confirm those release in Sonatype.  I just confirmed version 1.1.6 so now just waiting for Maven Central to update and show it.

**Comment by VovaStelmashchuk** [comment]
👍🏿
