### ISSUE TITLE
Could not update Growthbook for JVM beyond 1.1.1

### ISSUE THREAD

**Issue by edwardremo-chromedia** [growthbook/growthbook-kotlin#21]
I get this error upon building
```
> No matching variant of io.growthbook.sdk:GrowthBook:1.1.7 was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
```
is Growthbook still supported on JVM?
https://mvnrepository.com/artifact/io.growthbook.sdk/GrowthBook-jvm
also only lists 1.1.1

**Comment by eric239** [comment]
Hey GrowthBook team, any update on this? There are many of us out there using kotlin on the backend and looking to adopt GB

**Comment by vazarkevych** [comment]
We added support for the JVM. The new version 1.1.13 now is available.
Closing issue.
