### ISSUE TITLE
App crashes for Huawei devices on Android 10

### ISSUE THREAD

**Issue by rashidaattar** [growthbook/growthbook-kotlin#31]
Initialization library crashes , here's the log

Caused by androidx.startup.StartupException
java.lang.ClassNotFoundException: com.sdk.growthbook.AppContextProvider
androidx.startup.AppInitializer.discoverAndInitialize (AppInitializer.java:204)
androidx.startup.InitializationProvider.onCreate (InitializationProvider.java:42)
android.content.ContentProvider.attachInfo (ContentProvider.java:2097)
android.content.ContentProvider.attachInfo (ContentProvider.java:2070)
android.app.ActivityThread.installProvider (ActivityThread.java:8168)
android.app.ActivityThread.installContentProviders (ActivityThread.java:7709)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7573)
android.app.ActivityThread.access$2600 (ActivityThread.java:260)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2435)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8668)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1109)

**Comment by VovaStelmashchuk** [comment]
Can you provide a sample app with the problem ?

**Comment by tinahollygb** [comment]
Hi @rashidaattar, you may want to give the new Java SDK a try as it seems like your project may be having some version conflicts with the Kotlin SDK and the Android-related dependencies used. The new Java SDK does not have any Android or KMM-related dependencies, which may make it easier to integrate into your existing Android or KMM project.

- Docs: https://docs.growthbook.io/lib/java
- Repository: https://github.com/growthbook/growthbook-sdk-java
- JavaDoc: https://growthbook.github.io/growthbook-sdk-java

At the bottom of the docs page linked, there are links to JVM (Spring in Java, Ktor in Kotlin) and Android (Java) examples.

If you have any trouble or would like to provide any feedback, you can join us in our Slack group (https://slack.growthbook.io/) or create an issue on the Github repository for the Java SDK (https://github.com/growthbook/growthbook-sdk-java).

**Comment by Bohdan-Kim** [comment]
Could you please specify devices model. Are they running on HarmonyOS?
