### ISSUE TITLE
SDK is not casting attribute values to string

### ISSUE THREAD

**Issue by iciric** [growthbook/growthbook-kotlin#32]
When you create a new feature, set up the experiment and split users by `id` it seems that `defaultValue` is returned no matter what. After discussing it on GrowthBook's Slack channel we narrowed down the issue to the type of variable which is being passed. In our case type of `id` was `Long` which SDK didn't cast and could't do the split based on that. After we did the casting on our side everything was working fine.

[Discussion link](https://growthbookusers.slack.com/archives/C01T6PKD9C3/p1663077172920319)

Goal: Cast all attribute values to string to have unified approach

**Comment by vazarkevych** [comment]
Issue was fixed with new 1.1.18 release.
