### ISSUE TITLE
Growthbook SDK Minimum SDK version is 26 

### ISSUE THREAD

**Issue by diofelpallega** [growthbook/growthbook-kotlin#37]
I tried implementing io.growthbook.sdk:GrowthBook:1.0.3 on an app which supports min sdk 21 and I get this error,

Error: 
uses-sdk:minSdkVersion 21 cannot be smaller than version 26 declared in library [io.growthbook.sdk:GrowthBook-android:1.0.3] C:\Users\ASUS\.gradle\caches\transforms-3\969f30e38df6299befa3717181fb9170\transformed\jetified-GrowthBook-release\AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 26,
		or use tools:overrideLibrary="com.sdk.growthbook" to force usage (may lead to runtime failures)

  <uses-sdk
        android:minSdkVersion="26"
        android:targetSdkVersion="31" />

I saw on the documentation that this SDK supports both Java and Kotlin Android apps using Android SDK 21 and above. How do I get this to work?

**Comment by vazarkevych** [comment]
Hi.
The latest version is 1.1.18. Update the library and everything will work.

**Comment by diofelpallega** [comment]
Hi @vazarkevych  thanks for your reply. I'm getting `Unresolved reference: GBSDKBuilder`. do you have documentation on how to integrate growthbook for 1.1.18? All I can see is for `1.0.3` which is like this,

  var growthBook = GBSDKBuilder(
            apiKey = apiKey,
            hostURL = ATTRIBUTE_HOST_URL,
            attributes = attrs,
            trackingCallback = { _, _ ->
                // TODO: track in your analytics system
            }
        ).initialize()

**Comment by vazarkevych** [comment]
If you are using kotlin:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/94451639/196908716-be0f93ba-2f8a-41ce-90df-e011cf0bdd4b.png">
Use GBSDKBuilderApp instead of GBSDKBuilder.

**Comment by diofelpallega** [comment]
Thanks a lot for your fast reply @vazarkevych I'll check this out!

**Comment by vazarkevych** [comment]
Thank you to, I'll close this issue then.
