### ISSUE TITLE
Please update documentation for latest SDK version

### ISSUE THREAD

**Issue by amit3vedi** [growthbook/growthbook-kotlin#50]
i was using kotlin SDK version `io.growthbook.sdk:GrowthBook:1.0.3` because it's mentioned in [official documentation](https://docs.growthbook.io/lib/kotlin) page. but seems like actual latest version is 1.1.27 so i tried to migrate to 1.1.27 and my code is not working anymore 
I tried using exact same code provided on github readme file but that is also not working
```
var sdkInstance: GrowthBookSDK = GBSDKBuilderApp(apiKey = <API_KEY>,
    hostURL = <GrowthBook_URL>,
    attributes = <Hashmap>,
    trackingCallback = { gbExperiment, gbExperimentResult ->

}).initialize()
```
i tried to downgrade to version 1.1.23 and my code started working again. seems like in 1.1.23 version `GBSDKBuilderApp` class was in kotlin file so named arguments were supported but now it's java class file so it's not supported anymore. 
also even if i'm not using any encryption i have to pass encryption key value on latest 1.1.27 version?

**Comment by Bohdan-Kim** [comment]
Thank you for your report. We are working on it.

**Comment by Bohdan-Kim** [comment]
Since 1.1.28 version if you are not using any encryption you can pass `null` value.

**Comment by Bohdan-Kim** [comment]
In 1.1.34 version we returned back named parameters for GBSDKBuilder

**Comment by Bohdan-Kim** [comment]
The pull request was updated.
Doc for 1.1.43 version was just written.
[The pull request](https://github.com/growthbook/growthbook/pull/1424) still requires review.

**Comment by Bohdan-Kim** [comment]
It was finally merged. [Docs for 1.1.58 version](https://docs.growthbook.io/lib/kotlin).
@amit3vedi Do you have any other issues?
