### ISSUE TITLE
Doubts clarification and possible documentation update

### ISSUE THREAD

**Issue by Maciej-Monster** [growthbook/growthbook-kotlin#55]
Hi, I played around with Java & Kotlin SDKs. They are a bit different. In Java you have `GBFeaturesRepository` which is responsible for fetching & refreshing features. Then you create a context and pass attributes. 

Comparing to Kotlin SDK, there is no repository and only `GrowthBookSDK` has possibility to invoke `refreshCache` but it doesn't make sense as I need to create a new `GrowthBookSDK` so I will fetch features on my own and then pass it to the builder.

I experimenting with the SDK for a Kotlin server-side project.

Can you confirm there is no possibility to fetch features using your SDK? So basically do something similar as Java SDK allows.

**Comment by Bohdan-Kim** [comment]
Yep, it seems like GBFeaturesRepository should be added to Kotlin SDK

**Comment by tinahollygb** [comment]
> I experimenting with the SDK for a Kotlin server-side project.

You can also use the Java SDK with a Kotlin backend. [Here is an example for Ktor](https://github.com/growthbook/examples/tree/main/jvm-kotlin-ktor-example).

**Comment by Maciej-Monster** [comment]
Thanks all 👍  I ended up using Java SDK. Let's close the issue for now.
