### ISSUE TITLE
Gradle version 8 supporting

### ISSUE THREAD

**Issue by finberg** [growthbook/growthbook-kotlin#57]
Hi!
Is Gradle version 8 supported?
I have an error after adding growhbook-kotlin in an android project: 
`

* What went wrong:
Execution failed for task ':app:checkNormalDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.soywiz.krypto.AES found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.AES$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.HMAC found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.HMAC$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.Hash found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.Hash$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.Hasher found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.HasherFactory found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.HasherKt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD4 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD4$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD4$Companion$1 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD4Kt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD5 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD5$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD5$Companion$1 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.MD5Kt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.PBKDF2 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.PBKDF2$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.Padding found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.Padding$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.Padding$Companion$WhenMappings found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA1 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA1$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA1$Companion$1 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA1Kt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA256 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA256$Companion found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA256$Companion$1 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SHA256Kt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SecureRandom found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SecureRandomJvmKt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.SecureRandomKt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.encoding.ASCII found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.encoding.ASCIIKt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.encoding.Base64 found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.encoding.Base64Kt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.encoding.Hex found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.encoding.HexKt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     Duplicate class com.soywiz.krypto.internal.KryptoToolsKt found in modules krypto-debug-runtime-debug (com.soywiz.korlibs.krypto:krypto-android:2.7.0) and krypto-jvm-2.7.0 (com.soywiz.korlibs.krypto:krypto-jvm:2.7.0)
     
     Go to the documentation to learn h
`

**Comment by Bohdan-Kim** [comment]
According to the failure what about trying something like this:

    implementation('com.soywiz.korlibs.krypto:krypto-android:2.7.0') {
        exclude group: 'com.soywiz.korlibs.krypto', module: 'krypto-jvm'
    }

**Comment by Vladoslk** [comment]
Hi, it works fine with Gradle 8 for my case!
