### ISSUE TITLE
1.1.35 Not Uploaded to Maven Repository

### ISSUE THREAD

**Issue by HeinousGames** [growthbook/growthbook-kotlin#63]
[Here](https://mvnrepository.com/artifact/io.growthbook.sdk/GrowthBook-jvm) you can see that the last upload was 1.1.34. Please upload the latest version so that we may use it in our project. Thanks!

**Comment by Bohdan-Kim** [comment]
We are working on it. In successful case we'll notify you about new version. It will be 1.1.36 version. Waiting period: 1-2 days for release to appear on Maven. If you need it now you can use 1.1.34 version. The codebase will not change radically, there should not be any problems in upgrading to 1.1.36 version from 1.1.34.

**Comment by HeinousGames** [comment]
Thank you!
