### ISSUE TITLE
Deserialization issue in 1.1.38

### ISSUE THREAD

**Issue by ajsmithsw** [growthbook/growthbook-kotlin#75]
When running an experiment with a linked feature flag, there is a parsing issue in v1.1.38:
> Fields [name, passthrough] are required for type with serial name 'com.sdk.growthbook.Utils.GBVariationMeta', but they were missing at path: $.features['my-feature'].rules[0].meta[0] 

I have raised a potential fix for this here: https://github.com/growthbook/growthbook-kotlin/pull/74

**Comment by Bohdan-Kim** [comment]
We've started to work on the issue

**Comment by Bohdan-Kim** [comment]
According to the issue [this hotfix was made](https://github.com/growthbook/growthbook-kotlin/commit/c5085bb079676cae1349f408ba1116d1a47127ec).
