### ISSUE TITLE
Kotlin Multiplatform Project Library Support

### ISSUE THREAD

**Issue by jacksonej** [growthbook/growthbook-kotlin#88]
I can see that this project is based on KMP. However, when I try to add this library inside Kotlin Multiplatform shared code, I am getting an error like this:

`Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':shared:iosX64CompilationDependenciesMetadata'`

Is there any way we can make this work in a KMP project? Currently, my project supports Android and iOS

**Comment by Bohdan-Kim** [comment]
Could you please show the way you are adding this library inside Kotlin Multiplatform shared code?

**Comment by Bohdan-Kim** [comment]
Dear Jackson, 

This project was really started as KMP project initially. Then [Swift SDK](https://github.com/growthbook/growthbook-swift) appeared. Do you have ability to use Kotlin SDK for Android target and Swift SDK for iOS target in your KMP project? If you can add iOS support in Kotlin SDK create your pull request, please.

We will work on adding iOS distribution target too, but it seems like some troubles appeared between 1.1.1 and 1.1.13 versions of Kotlin SDK that lead to the absence of iOS distribution target.

**Comment by vazarkevych** [comment]
Hi, @jacksonej. We added functionality and provide [pull request](https://github.com/growthbook/growthbook-kotlin/pull/143) for it.
