### ISSUE TITLE
Feature Usage Callback

### ISSUE THREAD

**Issue by szeidner** [growthbook/growthbook-kotlin#89]
Other versions of the SDK seem to have a callback on feature usage (e.g. `onFeatureUsage` in the React SDK), but I didn't see an equivalent for the Kotlin SDK. Is this something that could be added?

**Comment by szeidner** [comment]
We use `onFeatureUsage` in React Native to log analytics when `useFeatureValue` is called.

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-kotlin/pull/101) was created according to this issue.
After new release the usage will be like:

![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/8f451ffc-44b5-476a-8ed9-50ceb0057e5c)

You can see the `'whether featureUsageCallback is called'` test for more info.
