### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LaurynasM-iproyal** [growthbook/growthbook-kotlin#90]
It seems that your documentation does not match latest version methods. It is most likely out dated. In addition, there is not enough explanation what each method do exactly and how everything works. 

I had to do extensive research of documentation and code to understand how to cover different cases. There are public methods annotated with DelicateCoroutinesApi and with 3 word comment explaining what they do and no documentation in any place...

My first problem was understanding how you manage to retrieve information without suspending threads. Then I assumed that you download all information on initialisation, but what if that fails? From testing I found out that it simply assumes that all features are OFF, because you did not download any. Then I found a method refreshCache. How to use it? What it does exatly? When to use it? How to check if your SDK failed to download? Then I found that there is a setRefreshHandler, which again is not documented anywhere. How to use it? Should I refreshCache there? It triggers with a Boolean and GBError, what errors I might expect to receive? Which should be recoverable, which means it is your SDK problem? 

So, I think it is safe to say, there are a million questions at every step of your SDK. Please spend some time and add more documentation or at least update it to latest version you have. Moreover, your website shows wrong/out dated version of library. Also, why does "growthbook-kotlin" project has documentation on how to work with your SDK on iOS?

**Comment by TianleZhang** [comment]
+1. I spent 2 days try to get it work with current documentation, but I couldn't get it work. I contact Growthbook and the they said this is managed by community, so basically I understood this is not their official supported. I really wonder if I want to put something like this into our product.

**Comment by Bohdan-Kim** [comment]
Yep, the documentation is not the best. We hope will find resources to improve it.


```
Moreover, your website shows wrong/out dated version of library.
```
[The pull request](https://github.com/growthbook/growthbook/pull/1424) to update docs on website was created.

**Comment by Bohdan-Kim** [comment]
```
Also, why does "growthbook-kotlin" project has documentation on how to work with your SDK on iOS?
```
Because this project was started as a Kotlin Multiplatform (KMM) project. KMM project is able to have iOS target.

**Comment by Bohdan-Kim** [comment]
```
There are public methods annotated with DelicateCoroutinesApi 
```
Thank you for pointing on this. We'll try to fix this in next release.

**Comment by vazarkevych** [comment]
> +1. I spent 2 days try to get it work with current documentation, and I couldn't get it work. I contact Growthbook and the they said this is managed by community, so basically I understood this is not their official supported. I really wonder if I want to put something like this into our product.

Hi, I’m pleased to announce that we have just uploaded new features: sticky bucketing and remote evaluation. We are also updating our documentation, which will soon be available on the website. We hope these updates will assist users of Growthbook. If you encounter any issues, please feel free to contact us in the Growthbook Slack channel #sdk-kotlin.

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-kotlin/pull/102) was created according to DelicateCoroutinesApi
