### ISSUE TITLE
Encrypted features are not being restored from disk cache

### ISSUE THREAD

**Issue by midery** [growthbook/growthbook-kotlin#98]
Hello! We recently discovered an issue with GrowthBook Android SDK: 

When we use encryption and save encrypted features to a disk cache, they're not being restored from it. This happens in [FeaturesViewModel.fetchFeatures](https://github.com/growthbook/growthbook-kotlin/blob/main/GrowthBook/src/commonMain/kotlin/com/sdk/growthbook/features/FeaturesViewModel.kt#L53) method: only `dataModel.features` is being restored, but dataModel.encryptedFeatures is being ignored. 
<img width="730" alt="Screenshot 2024-04-23 at 11 47 40" src="https://github.com/growthbook/growthbook-kotlin/assets/4126621/3eb9e194-9e57-4ab6-ad52-15e04ff700ef">
This results in incorrect state if we read some values right after app start, before we fetch the updated value from a remote. 

Reproducible steps: 
1. Use `encryptionKey` when initializing GrowthbookSDK
2. Run your application once to fetch the data and save this data on disk.
3. Try to read feature value right after initialization

**Expected behavior:** 
`GrowthbookSDK.getFeatures()` returns previously fetched features, feature's source is the source from last remote call. 
**Actual behavior:**
`GrowthbookSDK.getFeatures()` returns empty map, feature's source is "unknownFeature"

Is this an intentional behavior? If it is not, can you please take a look into it? 🙏

**Comment by Bohdan-Kim** [comment]
Hello @midery!
Thank you for reporting. Could you please specify the version of the SDK you are using?

**Comment by Bohdan-Kim** [comment]
Hello!
Thanks for reporting this.
The problem to just hotfix this is that `features` and `encryptedFeatures` has different types. The same is on Swift SDK.
Do you have iOS dev in your team or you are working without iOS devs? Seems like iOS dev [will see the same](https://github.com/growthbook/growthbook-swift). We try to keep SDKs similar.

**Comment by Bohdan-Kim** [comment]
Hello @midery!
Thanks for reporting this. Could you please specify SDK version you found this issue on?

**Comment by Bohdan-Kim** [comment]
The encrypted features are transferred over the network while you are always pointing us to the restoring features from cache. I would agree if it will be encrypted features from Backend but you are pointing to the features from cache.

**Comment by Bohdan-Kim** [comment]
Could you please try to reproduce on [1.1.47 version](https://mvnrepository.com/artifact/io.growthbook.sdk/GrowthBook/1.1.47)? There should be [Fix encrypted features preparation](https://github.com/growthbook/growthbook-kotlin/pull/94)

**Comment by Bohdan-Kim** [comment]
We need to investigate it a little bit deeper

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-kotlin/pull/99) was created according to this issue.
